"""
initial migration: create tables from models_v3 metadata

This migration was generated by hand because the configured database
was not reachable during `alembic revision --autogenerate`.

It creates all tables defined on `agriconnect.services.models_v3.Base`.

Original manual SQL files have been preserved under:
  src/agriconnect/database/legacy_sql_backup/

Review before applying to any production database.

# Correspondence to legacy SQL backups (review these when validating migration):
# - audit_trail.sql                : audit and history tables / triggers
# - enable_pgvector.sql           : pgvector extension setup (run separately)
# - init.sql                      : initial schema snippets used historically
# - marketplace*.sql              : marketplace tables and seeds
# - memory_migration.sql          : memory / embeddings metadata migrations
# - migration_*.sql               : assorted feature migrations (see filenames)
# - patch_add_userid_conversations.sql : ad-hoc patch for conversations.user_id
# - protocol_tables.sql           : protocol/tooling tables used by MCP
# - seed_sesame_sorgho.sql        : example data seed
#
# When applying this autogenerated migration, verify:
# 1) Required extensions (pgvector) are created beforehand via enable_pgvector.sql
# 2) Any manual data-migration steps in `migration_*.sql` are executed in the correct order
# 3) Constraints and FK creation ordering matches production expectations
# 4) Add comments linking these SQL chunks to specific table definitions if needed
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial_from_models_v3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Import models and create all tables. This avoids needing an active
    # connection during revision generation. Review generated schemas.
    bind = op.get_bind()
    try:
        # Import here to avoid import-time DB connections in env.py
        from agriconnect.services import models_v3
    except Exception:
        # Fallback: try alternate import path used by tests/runtime
        from src.agriconnect.services import models_v3

    models_v3.Base.metadata.create_all(bind=bind)


def downgrade():
    bind = op.get_bind()
    try:
        from agriconnect.services import models_v3
    except Exception:
        from src.agriconnect.services import models_v3

    # Dropping all tables is destructive; review before running in prod.
    models_v3.Base.metadata.drop_all(bind=bind)
